FROM openjdk:17
LABEL maintainer="prabashswarnajith2001@gmail.com"
WORKDIR /app
COPY target/spring-boot-mariadb-0.0.1-SNAPSHOT.jar /app/spring-boot-mariadb-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "spring-boot-mariadb-0.0.1-SNAPSHOT.jar"]
